language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'node'
install:
  - yarn
  - yarn global add codecov
script:
  - yarn test -- --coverage
  - yarn build
after_success:
  - codecov